[package]
name = "lox-rs"
version = "0.1.0"
authors = ["rawcptr"]
edition = "2021"
rust-version = "1.80"

[dependencies]
bytes = "1.10.1"
clap = { version = "4.5.39", features = ["derive"] }
miette = { version = "7.6.0", features = ["fancy"] }
